language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/chatelao/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit Arduino Zero ASF Core Library"
script:
  - build_platform zero
notifications:
  email:
    on_success: change
    on_failure: change
